//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelicatescoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDetails()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public double Weight { get; set; }
        public int PackageId { get; set; }
        public string StorageConditions { get; set; }
        public int NutritionalValueId { get; set; }
        public int EnergyValue { get; set; }
        public string Сompound { get; set; }
    
        public virtual NutritionalValue NutritionalValue { get; set; }
        public virtual Package Package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
